config/routes.rb
WaukeeSurvey::Application.routes.draw do

	match "/" => "users#index"

	resources :polls do
		resources :questions do
			resources :options
		end
	end

	resources :users
	resources :votes

	post "/users/login" => "users#login"

	post "/polls/:poll_id/questions/new" => "questions#create"
	post "/polls/:poll_id/questions/:id/edit" => "questions#update"
	post "/polls/:poll_id/questions/:question_id/options/new" => "options#create"
	post "/polls/:poll_id/questions/:question_id/options/:id/edit" => "options#update"

end

app/models/option.rb
class Option < ActiveRecord::Base
	attr_accessible :title

	belongs_to :questions
end

app/models/poll.rb
class Poll < ActiveRecord::Base
	attr_accessible :title
	
	belongs_to :users
	has_many :questions, :dependent => :destroy
	has_many :options, :dependent => :destroy
end

app/models/question.rb
class Question < ActiveRecord::Base
	attr_accessible :title

	belongs_to :polls
	has_many :options, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :username, :password

	has_many :polls, :dependent => :destroy
	has_many :questions, :dependent => :destroy
	has_many :options, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

def index
	
end

def show
	@option = Option.find(params[:id])
end

def new
	@option = Option.new
	@poll = Poll.find(params[:poll_id])
	@question = Question.find(params[:question_id])
end

def create
	@question = Question.find(params[:question_id])
	@option = @question.options.new(params[:option])
	if @option.save
		redirect_to poll_questions_path
	else
		redirect_to new_poll_question_option_path
	end
end

def edit
	@option = Option.find(params[:id])
end

def update
	@option = Option.find(params[:id])
	if @option.update_attributes(params[:option])
		redirect_to poll_questions_path
	else
		redirect_to :back
	end
end

def destroy
	@option = Option.find(params[:id])
	@option.destroy
	redirect_to poll_questions_path
end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

def index
	@polls = Poll.all
end

def show
	@poll = Poll.find(params[:id])
end

def new
	@poll = Poll.new
end

def create
	@poll = Poll.new(params[:poll])
	if @poll.save
		redirect_to polls_path
	else
		redirect_to new_poll_path
	end
end

def edit

end

def update

end

def destroy

end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

def index
	@poll = Poll.find(params[:poll_id])
	@questions = @poll.questions.all
	@options = []
	@questions.each do |question|
		@qOptions = question.options.all
		@options.push(@qOptions)
	end
end

def show
	@poll = Poll.find(params[:poll_id])
	@question = Question.find(params[:id])
end

def new
	@question = Question.new
	@poll = Poll.find(params[:poll_id])
end

def create
	@poll = Poll.find(params[:poll_id])
	@question = @poll.questions.new(params[:question])
	if @question.save
		redirect_to poll_questions_path
	else
		redirect_to new_poll_question_path
	end
end

def edit
	@question = Question.find(params[:id])
end

def update
	@question = Question.find(params[:id])
	if @question.update_attributes(params[:question])
		redirect_to poll_questions_path
	else
		redirect_to edit_poll_question_path
	end
end

def destroy
	@question = Question.find(params[:id])
	@options = Option.find(:all, :conditions => ['question_id = ?', params[:id]])
	@options.each do |option|
		option.destroy
	end
	@question.destroy
	redirect_to poll_questions_path
end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
	if params[:username]
		@user = User.find(:conditions => [:username => params[:username]])
	end
end

def show
	
end

def new
	@user = User.new
end

def create
	@user = User.new(params[:user])
	@checkName = User.find(:all, :conditions => ['username = ?', params[:username]])
		if @user.save
			redirect_to users_path
		else
			redirect_to new_user_path
		end
end

def edit

end

def update

end

def destroy

end

def login
	@supposedUser = User.find(:all, :conditions => ['username = ?', params[:username]])
	@supposedUser.each do |user|
		if params[:password] == user.password
			session[:user_id] = user.id
			redirect_to users_path
		end
	end
end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaukeeSurvey</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<br>
<br>
<br>
<%= link_to "Home", polls_path %>
</body>
</html>

app/views/options/edit.html.erb
<h1>Edit "<%= @option.title %>" option</h1>

<%= form_for :option do |f| %>
	Option:<%= f.text_field :title %>
	<br>
	<%= f.submit "Edit option" %>
<% end %>

app/views/options/new.html.erb
<h1>New option for "<%= @question.title %>" in the "<%= @poll.title %>" poll</h1>

<%= form_for :option do |f| %>

	Option: <%= f.text_field :title %> 
	<br>
	<%= f.submit "Add option" %>

<% end %>

app/views/polls/index.html.erb
<h1>All polls</h1>
<%= link_to "Create a new poll", new_poll_path %>
<br>

<% @polls.each do |poll| %>
<div class="poll">
<%= link_to poll.title, poll_questions_path(poll) %>
<br>
<br>
</div>

<% end %>

app/views/polls/new.html.erb
<h1>Create a new poll</h1>

<%= form_for @poll do |f| %>
	
	Poll name: <%= f.text_field :title %>
	<br>
	<%= f.submit %>

<% end %>

app/views/questions/edit.html.erb
<h1>Edit "<%= @question.title %>" question</h1>

<%= form_for :question do |f| %>
	Question:<%= f.text_field :title %>
	<br>
	<%= f.submit "Edit question" %>
<% end %>

app/views/questions/index.html.erb
<h1>All questions for "<%= @poll.title %>" poll</h1>

<% @questions.each do |question| %>
	<div class="question">
	<%= question.title %> <%= link_to "Edit", edit_poll_question_path(@poll,question) %> <%= link_to "Delete", poll_question_path(@poll,question), :method => :delete, :confirm => "Are you sure you want to delete?" %>
	<br>
	<ul>
	<% @options.each do |thisoptionarray| %>
		<% thisoptionarray.each do |option| %> 
			<% if option.question_id == question.id %>
				<% @optiondivname = option.id.to_s + "div" %>
				<li id="<%= option.id %>"><%= option.title %> <%= link_to "Edit", edit_poll_question_option_path(@poll,question,option) %> <%= link_to "Delete", poll_question_option_path(@poll,question,option), :method => :delete, :confirm => "Are you sure you want to delete?" %></li>
				<script type="text/javascript">
					
				</script>
				<div id="<%= @optiondivname %>">

				</div>
			<% end %>
		<% end %>
	<% end %>
	</ul>
	<%= link_to "Add new option", new_poll_question_option_path(@poll,question) %>
	</div>
<% end %>

<%= link_to "Add new question", new_poll_question_path(@poll) %>

app/views/questions/new.html.erb
<h1>New question for "<%= @poll.title %>" poll</h1>

<%= form_for :question do |f| %>
	
	Question: <%= f.text_field :title %> 
	<br>
	<%= f.submit "Add question" %>

<% end %>

app/views/users/index.html.erb
<h1>Waukee Surveying</h1>

<form method="post" action="/users/login" class="login" id="login">
Username: <input type="text" name="username" /> Password: <input type="password" name="password" />
<input type="submit" value="Login" />
</form>

<%= session[:user_id] %>

<%= link_to "Create an account", new_user_path %>

app/views/users/new.html.erb
<h1>Make a new account</h1>

<%= form_for @user do |f| %>

	Desired username: <%= f.text_field :username %>
	<br>
	Password: <%= f.password_field :password %>
	<br>
	<%= f.submit "Sign up" %>
	

<% end %>